version: '3.9'

services:
  app:
    build: .
    container_name: react-test
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    # command: sh -c "npm i && npm run dev -- --host"

    # # Ajuste opcional para reiniciar sempre em caso de falha
    # restart: always
